### ISSUE TITLE
streamlit': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by natea** [richieyoum/superknowba#8]
I followed the instructions in the README, and got this error:

```
$ python streamlit app.py
/Users/nateaune/.pyenv/versions/superknowba/bin/python: can't open file '/Users/nateaune/Documents/code/superknowba/streamlit': [Errno 2] No such file or directory
```

Then I tried just running `app.py`:

```
$ python app.py

2023-08-11 11:32:13.520 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
2023-08-11 11:32:13.527
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run app.py [ARGUMENTS]
Traceback (most recent call last):
  File "/Users/nateaune/.pyenv/versions/superknowba/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 378, in __getitem__
    return self._getitem(widget_id, key)
  File "/Users/nateaune/.pyenv/versions/superknowba/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 423, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nateaune/Documents/code/superknowba/app.py", line 24, in <module>
    sidebar()
  File "/Users/nateaune/Documents/code/superknowba/superknowba/components/sidebar.py", line 46, in sidebar
    ["ChatGPT"] + st.session_state["database_list"],
  File "/Users/nateaune/.pyenv/versions/superknowba/lib/python3.10/site-packages/streamlit/runtime/state/session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
  File "/Users/nateaune/.pyenv/versions/superknowba/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 113, in __getitem__
    return self._state[key]
  File "/Users/nateaune/.pyenv/versions/superknowba/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 380, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "database_list". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'
```

Lastly I ran the following command and this one worked:

```
$ streamlit run app.py
```

**Comment by richieyoum** [comment]
Hi @natea, thanks for the flag. This is actually just an error on the `README.md`, as streamlit application is meant to be started using `streamlit run app.py` like you mentioned without the initial `python` call in front.

**Comment by richieyoum** [comment]
Addressed in https://github.com/richieyoum/superknowba/pull/10
